### ISSUE TITLE
GDB support is broken

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#666]
Tested in a clean K 5.5.102 docker image, following the instructions in lesson 19 D of the K tutorial:

```
(gdb) k match LESSON-19-D.baz subject
Traceback (most recent call last):
  File "<string>", line 392, in to_string
  File "<string>", line 566, in append
gdb.MemoryError: Cannot access memory at address 0x7ffea8ecb000

Subject:
<error reading variable: Cannot access memory at address 0x7ffea8ecb000>
does not match pattern:
_:KCell
```

**Comment by Baltoli** [comment]
Not an issue, in fact - example reproduction was using `-O0` rather than `-O1` which breaks things.
