### ISSUE TITLE
[GDB] Can't print `string` and `int` on LHS of rules in `K Match`

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/llvm-backend#746]
Given the K definition:
```
module TEST
  imports INT
  imports STRING
  
  syntax Foo ::= foo(Int)
  syntax FooString ::= fooString(String)

  rule [test]: foo(42) => .K
  rule [testString]: fooString("Hello World!") => .K
endmodule
```

Kompile:
```
kompile test.k --enable-llvm-debug --syntax-module TEST
```

Krun and GDB with Int:
```
krun -cPGM='foo(0)' --debugger

(gdb) k start
...
(gdb) k match TEST.test subject
INT.size_int(0) => 0
Traceback (most recent call last):
  File "<string>", line 794, in invoke
gdb.error: No type named SortMInt{Sort32{}}.

Python Exception <class 'gdb.error'>: No type named SortMInt{Sort32{}}.
Error occurred in Python: No type named SortMInt{Sort32{}}
```

Krun and GDB with String:
```
 krun -cPGM='fooString("Hi")' --debugger 

(gdb) k start
...
(gdb) k match TEST.testString subject
KEQUAL.eq(0x7ffff5400080, 0x2e5310 <token_48656c6c6f20576f726c6421>) => false
Traceback (most recent call last):
  File "<string>", line 794, in invoke
gdb.error: No type named .

Python Exception <class 'gdb.error'>: No type named .
Error occurred in Python: No type named .
```

**Comment by Robertorosmaninho** [comment]
Wrong debug information when pattern matching `bool` in LHS of a rule:

```
module TEST
  imports BOOL

  syntax FooBool ::= fooBool(Bool)
  rule [testPatternBool]: fooBool(true) => .K
end module
```

Kompile:
```
kompile test.k --enable-llvm-debug --syntax-module TEST
```

krun and GDB:
```bash
krun -cPGM='fooBool(false)' --debugger
(gdb) k start
...
(gdb) k match TEST.testPatternBool subject
Subject:
true # should be false
does not match pattern:
true
(gdb)

```

**Comment by Robertorosmaninho** [comment]
Can't output a `List` subject when the `k match` fails on a rule with a `List` in its LHS:

```
module TEST
  imports BOOL

  syntax FooList ::= fooPatternList(List)
  rule [testPatternList]: fooPatternList(.List) => .K
end module
```

Kompile:
```bash
kompile test.k --enable-llvm-debug --syntax-module TEST
```

krun and GDB:
```bash
krun -cPGM='fooPatternList(ListItem(0))' --debugger 
(gdb) k start
...
(gdb)k match TEST.testPatternList subject
LIST.size_long(ListItem ( 0 )) => 0
Traceback (most recent call last):
  File "<string>", line 794, in invoke
gdb.error: No type named SortMInt{Sort64{}}.

Python Exception <class 'gdb.error'>: No type named SortMInt{Sort64{}}.
Error occurred in Python: No type named SortMInt{Sort64{}}.
```

**Comment by Robertorosmaninho** [comment]
Can't output a `Map` subject when the `k match` fails on a rule with a `Map` in its LHS:

```
module TEST
  imports MAP

  syntax FooMap ::= fooPatternMap(Map)
  rule [testPatternList]: fooPatternList(.List) => .K
end module
```

Kompile:
```bash
kompile test.k --enable-llvm-debug --syntax-module TEST
```

krun and GDB:
```bash
krun -cPGM='fooPatternMap(0|-> 0)' --debugger
(gdb) k start
...
(gdb) k match TEST.tesPatterntMap subject
MAP.size_long(0 |-> 0) => 0
Traceback (most recent call last):
  File "<string>", line 794, in invoke
gdb.error: No type named SortMInt{Sort64{}}.

Python Exception <class 'gdb.error'>: No type named SortMInt{Sort64{}}.
Error occurred in Python: No type named SortMInt{Sort64{}}.
```

**Comment by Robertorosmaninho** [comment]
Can't output a `Set` subject when the `k match` fails on a rule with a `Set` in its LHS:

```
module TEST
  imports SET

  syntax FooSet ::= fooSet(Set)
  rule [testPatternSet]: fooSet(.Set) => .K
end module
```

Kompile:
```bash
kompile test.k --enable-llvm-debug --syntax-module TEST
```

krun and GDB:
```bash
krun -cPGM='fooSet(SetItem(0))' --debugger  
(gdb) k start
...
(gdb) k match TEST.testPatternSet subject
SET.size_long(SetItem ( 0 )) => 0
Traceback (most recent call last):
  File "<string>", line 794, in invoke
gdb.error: No type named SortMInt{Sort64{}}.

Python Exception <class 'gdb.error'>: No type named SortMInt{Sort64{}}.
Error occurred in Python: No type named SortMInt{Sort64{}}.
```

**Comment by Robertorosmaninho** [comment]
A possible idea to solve this is to declare the possible sorts (arguments on this phi function) as global variables...
Any thoughts on this @Baltoli?

**Comment by Baltoli** [comment]
I don't fully understand why this code is trying to print out the sort `MInt{64}`. Can you remind me of what's going on here?

**Comment by Robertorosmaninho** [comment]
Of course! I can say for sure about this `rule [test]: foo(42) => .K` the idea when using `krun -cPGM='foo(0)' --debugger` would be to print the `0` as subject and the `42` as the pattern. However, we have this error when we try to print the subject. 

- The error within string is that both `sort` and `pattern` are empty (the result of their phi function)
- Same for Float
- Can't remember for Bool
- Neither for Set, Map, List. Although, I have a hard intuition that at least these 3 have the same issue. (Hopefully, fixing the first integer problem, this issue will be fixed as well, or at least closer to a fix.)

**Comment by Robertorosmaninho** [comment]
That's the final type of the subject phi function. We try to cast the subject to `MInt{...}`

**Comment by Baltoli** [comment]
So the problem is that the match function is not setting the sort and pattern correctly on _failing_ log entries when testing the match - is that correct?

**Comment by Baltoli** [comment]
Well, I guess the fix is to look at the function that populates the match log and identify why it fails to set the log entries correctly and falls through to the final case.

**Comment by Robertorosmaninho** [comment]
Yeah, I would like a hand on this, I've already tried it a lot and have yet to come up with any solutions...

**Comment by Baltoli** [comment]
Reinvestigate now that the LLVM 16 opaque pointers change has been merged.
