### ISSUE TITLE
LLVM Backend crashes when creating proof hints.

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/llvm-backend#800]
When running the interpreter with the `--proof-output` flag, I get the following stacktrace:

```#0  0x000055c019273f67 in storeSymbolChildren ()
(gdb) bt
#0  0x000055c019273f67 in storeSymbolChildren ()
#1  0x000055c0192938da in constructCompositePattern (tag=tag@entry=346, arguments=std::vector of length 1, capacity 1 = {...})
    at /home/njr/co/github.com/kframework/proof-generation/deps/k/llvm-backend/src/main/native/llvm-backend/runtime/util/ConfigurationParser.cpp:77
#2  0x000055c0192a0068 in serializeRawTermToFile (filename=0x7fff2c0ef488 "/tmp/.krun-2023-07-11-12-26-25-CS8ulZl9oQ/result.kore", subject=0x0,
    sort=<optimized out>)
    at /home/njr/co/github.com/kframework/proof-generation/deps/k/llvm-backend/src/main/native/llvm-backend/runtime/util/ConfigurationSerializer.cpp:443
#3  0x000055c01925af4e in apply_rule_2896 ()
#4  0x000055c01928042c in take_steps ()
#5  0x000055c01929315c in main ()
```

```njr@kraken$ kompile --backend llvm examples/imp/imp.k
njr@kraken$ krun --dry-run examples/imp/sum.imp
./imp-kompiled/interpreter /tmp/.krun-2023-07-11-12-32-41-fJ1e2VVdQ7/tmp.in.7sPzSReUVJ -1 /tmp/.krun-2023-07-11-12-32-41-fJ1e2VVdQ7/result.kore
njr@kraken$ ./imp-kompiled/interpreter /tmp/.krun-2023-07-11-12-32-41-fJ1e2VVdQ7/tmp.in.7sPzSReUVJ -1 /tmp/.krun-2023-07-11-12-32-41-fJ1e2VVdQ7/result.kore
njr@kraken$ ./imp-kompiled/interpreter /tmp/.krun-2023-07-11-12-32-41-fJ1e2VVdQ7/tmp.in.7sPzSReUVJ -1 /tmp/.krun-2023-07-11-12-32-41-fJ1e2VVdQ7/result.kore --proof-output
Segmentation fault (core dumped)
```

Running without the flag succeeds.
[sum.imp.txt](https://github.com/runtimeverification/llvm-backend/files/12018621/sum.imp.txt)
[imp.k.txt](https://github.com/runtimeverification/llvm-backend/files/12018622/imp.k.txt)

**Comment by nishantjr** [comment]
Sorry, I was using the inccorrect version of K.
